ame: dashboard-test
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib-base
  - pandas
  - ipywidgets
  - jupyterlab>=3.1
  - voila>=0.2.11
  - ipykernel
  - nbclient
  - nbconvert
  - jupyter-server
